[build]
  base = "dev-portfolio"
  command = "bun install && bun run build"
  publish = ".svelte-kit/netlify"
  
[build.environment]
  NETLIFY_USE_BUN = "true"
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
